name: superperms
adopt-info: superperms
summary: Search for minimal Super Permutations
description: |
  Search for minimal Super Permutations as part of a distributed computing project. More information can be found in these videos:

  - Numberphile (https://www.youtube.com/watch?v=wJGE4aEWc28)
  - Standupmaths (https://www.youtube.com/watch?v=OZzIvl1tbPo)

  This article (https://www.quantamagazine.org/sci-fi-writer-greg-egan-and-anonymous-math-whiz-advance-permutation-problem-20181105/) in Quanta magazine also explains.

  The search is based upon these research papers:

  - Nathaniel Johnston (https://arxiv.org/abs/1303.4150)
  - Robin Houston (https://arxiv.org/abs/1408.5108)

  This snap was created by the Ubuntu Podcast community. We would be grateful if you could join the "Ubuntu Podcast" collective for this search so we can "win", but this is optional. Please also give the Ubuntu Podcast a listen in your podcatcher or at https://ubuntupodcast.org/, and maybe join our Telegram chatroom with an invite located at https://ubuntupodcast.org/telegram/

  Statistics for the search and team leaderboard (http://www.supermutations.net/ChaffinMethodResults/).

  To run with your team set to Ubuntu Podcast:

  `superperms team "Ubuntu Podcast"`

  The default team is "Anonymous".

  You can tell the program to run for a specified number of minutes, after which it will **wait to finish the current task before quitting**:

  `superperms timeLimit 120 team "Ubuntu Podcast"`

  This would tell the program to run for 120 minutes and then quit, **after it has finished its current task**.

  You can also enforce a stricter time limit, using the option timeLimitHard:

  `superperms timeLimitHard 120 team "Ubuntu Podcast"`

  With this the program will run for 120 minutes and quit, within about 5 minutes of that quota, **even if** it is in the middle of a task.

  A single client will use one CPU core, so if you want to dedicate more CPU time to the search you need to run the client multiple times - the standard is to run one client per CPU core in your PC.

  This app will eat batteries on a laptop or tablet computer so it is advisable not to run this on such devices if they are not plugged-into a stable power outlet. The search will also produce a lot of heat.

  The source code for this client is on GitHub (https://github.com/superpermutators/superperm).

  Ongoing discussion about the search is held in the Google Group (https://groups.google.com/forum/#!forum/superpermutators).

base: core
grade: stable
confinement: strict

parts:
  superperms:
    source: https://github.com/superpermutators/superperm.git
    source-subdir: DistributedChaffinMethod
    plugin: make
    build-packages:
    - gcc
    stage-packages:
    - curl
    override-pull: |
      snapcraftctl pull
      cd DistributedChaffinMethod
      cat <<EOF> launch.sh
      #!/bin/bash
      set -e
      cd \$SNAPCRAFT_USER_COMMON
      \$SNAP/DistributedChaffinMethod "\$@"
      EOF
      snapcraftctl set-version "$(grep 'Current version:' DistributedChaffinMethod.c | sed -e 's/Current version: //')"
    override-build: |
      cd DistributedChaffinMethod
      make
      install -m755 -T DistributedChaffinMethod $SNAPCRAFT_PART_INSTALL/DistributedChaffinMethod
      install -m755 -T launch.sh $SNAPCRAFT_PART_INSTALL/launch.sh

apps:
  superperms:
    command: launch.sh
    plugs:
    - network